## About Numpy

NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

## Why Numpy?

Although Python lists are excellent, general-purpose containers. They can be `heterogeneous`, meaning that they can contain elements of a variety of types.

On the other hand, most NumPy arrays have some restrictions. For instance:
- They must be `homogeneous`, i.e. All elements of the array must be of the same type of data.
- Once created, the total size of the array can’t change.
- The shape must be `rectangular`, not jagged; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks.

## Installing and Importing

To install Numpy as a package:

```shell
pip install numpy
```

To import numpy:

In [1]:
import numpy as np

## Operations

#### Initialising a new Array

One way to initialize an array is using a Python sequence, such as a list.
to initialize an array from a list, we use np.array()

In [10]:
myList = [1, 2, 3]
print(type(myList))
a = np.array(myList, dtype='int8')
print(type(a))

# prints the numpy array
print(f"array = {a}\n")

# to get the dimension of the array
print("dimensions = ", a.ndim)

# to get the order of the array
print("shape = ", a.shape)

# to get the data type of the array
print("data type = ", a.dtype)

# to get the no of elements in the array
print("no of elements: ", len(a))
print("no of elements: ", a.size)

# to get the memory size of each element in bytes
print("size of each elements: ", a.itemsize)

# to get the memory size of the array in bytes
print("size of array: ", a.size * a.itemsize)
print("size of array: ", a.nbytes)


<class 'list'>
<class 'numpy.ndarray'>
array = [1 2 3]

dimensions =  1
shape =  (3,)
data type =  int8
no of elements:  3
no of elements:  3
size of each elements:  1
size of array:  3
size of array:  3


In [ ]:
# we can also initialize an multi-dimensional array
b = np.array([[9.1, 8.2, 7.3], [3.7, 2.8, 1.9]], dtype="float32")
print(f"{b}\n")

# to get the dimension of the array
print("\ndimensions = ", b.ndim)

# to get the order of the array
print("shape = ", b.shape)

# to get the data type of the array
print("data type = ", b.dtype)

[[9.1 8.2 7.3]
 [3.7 2.8 1.9]]


dimensions =  2
shape =  (2, 3)
data type =  float32


Another way to initialize an array is to use list comprehension along with np.array()

In [16]:
c = np.array([2*i+2 for i in range(50)])
print(c)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


#### Reshaping

In [23]:
before = np.array([[6, 1, 8, 0], [3, 9, 8, 7]])
print(before)
print(f"shape = {before.shape}\ndim = {before.ndim}\n")

after = before.reshape((4,2)) # it is Not the same as transpose
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((1, 8)) # it still is 2D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((8)) # now it is 1D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((2, 2, 2)) # now it is 3D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

#after = before.reshape((2, 3))
# this causes error as the no of elements dont match

[[6 1 8 0]
 [3 9 8 7]]
shape = (2, 4)
dim = 2

[[6 1]
 [8 0]
 [3 9]
 [8 7]]
shape = (4, 2)
dim = 2

[[6 1 8 0 3 9 8 7]]
shape = (1, 8)
dim = 2

[6 1 8 0 3 9 8 7]
shape = (8,)
dim = 1

[[[6 1]
  [8 0]]

 [[3 9]
  [8 7]]]
shape = (2, 2, 2)
dim = 3



#### Intialising special arrays

In [30]:
print("nd array with all zeros")
m = np.zeros((3, 4))
print(m)
print(f"Default data type = {m.dtype}\n")

print("nd array with all zeros")
m = np.ones((3, 4))
print(m)
print(f"Default data type = {m.dtype}\n")

print("nd array with all same value")
value = 7
m = np.full((3, 4), value)
print(m)
print(f"Default data type = {m.dtype}\n")

print("nd array as identity matrix")
m = np.identity(4)
print(m)
print(f"Default data type = {m.dtype}\n")

nd array with all zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Default data type = float64

nd array with all zeros
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Default data type = float64

nd array with all same value
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Default data type = int64

nd array as identity matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Default data type = float64



In [32]:
print("nd array with")
m = np.random.rand(3, 4)
print(m)
print(f"Default data type = {m.dtype}\n")

print("nd array with")
m = np.random.randint(1, 7, size=(3, 4))
print(m)
print(f"Default data type = {m.dtype}\n")

nd array with
[[0.71991849 0.46819962 0.47026018 0.80041042]
 [0.64789412 0.21594941 0.7028744  0.07073741]
 [0.86243034 0.02341757 0.36481851 0.59544851]]
Default data type = float64

nd array with
[[6 2 4 2]
 [5 2 4 1]
 [3 1 1 2]]
Default data type = int32



#### Making copy of an array

In [ ]:
# shallow copy
print("before")

a = np.array([1, 2, 3, 4])
print("a = ", a)

s = a
print("s = ", s)

a[1] = 100
s[2] = 200

print("after")
print("a = ", a)
print("s = ", s)

before
a =  [1 2 3 4]
s =  [1 2 3 4]
after
a =  [  1 100 200   4]
s =  [  1 100 200   4]


In [48]:
# deep copy
print("before")
a = np.array([1, 2, 3, 4])
print("a = ", a)

b = np.array(a)
print("b = ", b)
c = a.copy()
print("c = ", c)

a[0] = 100
b[1] = 200
c[2] = 300

print("after")
print("a = ", a)
print("b = ", b)
print("c = ", c)

before
a =  [1 2 3 4]
b =  [1 2 3 4]
c =  [1 2 3 4]
after
a =  [100   2   3   4]
b =  [  1 200   3   4]
c =  [  1   2 300   4]


#### Indexing in arrays

In [ ]:
arr = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(arr, "\n")

print("Dimensions of the array: ",arr.shape) # (3, 4)

# using indexing to print elements individually

print("\nUsing [i][j] notation")
for i in range (arr.shape[0]):
    for j in range (arr.shape[1]):
        print(arr[i][j], end = "  ")
    print("")

print("\nUsing [i, j] notation")
for i in range (arr.shape[0]):
    for j in range (arr.shape[1]):
        print(arr[i, j], end = "  ")
    print("")

1
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]] 

Dimensions of the array:  (3, 4)

Using [i][j] notation
11  12  13  14  
21  22  23  24  
31  32  33  34  

Using [i, j] notation
11  12  13  14  
21  22  23  24  
31  32  33  34  


In [43]:
a = np.array([6, 1, 8, 0, 3, 9, 8, 8, 7])

print(a)
print(a[2])
print(a[2], a[3], a[4])
print(a[2:5])
print(a[2:])
print(a[:5])
print(a[0:7:2])
print(a[::-1])


[6 1 8 0 3 9 8 8 7]
8
8 0 3
[8 0 3]
[8 0 3 9 8 8 7]
[6 1 8 0 3]
[6 8 3 8]
[7 8 8 9 3 0 8 1 6]


In [45]:
arr = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print("Dimensions of the array: ",arr.shape) # (3, 4)
print("arr = \n", arr)

# to get a specific row
print("\nPrinting Specific Rows")
print(arr[0])
print(arr[2, :])

# to get a specific column
print("\nPrinting Specific Cols")
print(arr[:, 0])
print(arr[:, 2])

# to get a specific sub-matrices
print("\nPrinting Specific submatrices")
print(arr[0:2, 1:3])

Dimensions of the array:  (3, 4)
arr = 
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

Printing Specific Rows
[11 12 13 14]
[31 32 33 34]

Printing Specific Cols
[11 21 31]
[13 23 33]

Printing Specific submatrices
[[12 13]
 [22 23]]


`Note:` The more you use ranged indexing the more dimensions the ouput array will have

#### Stacking

In [46]:
# 1D arrays
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(np.row_stack([v1, v2, v2])) # `row_stack` alias is deprecated. Use `np.vstack` directly.
print()
print(np.vstack([v1, v2, v2]))
print()
print(np.hstack([v1, v2, v2]))
print()
print(np.column_stack([v1, v2, v2]))
print()

[[1 2 3]
 [4 5 6]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [4 5 6]]

[1 2 3 4 5 6 4 5 6]

[[1 4 4]
 [2 5 5]
 [3 6 6]]



C:\Users\dell\AppData\Local\Temp\ipykernel_13416\3801226394.py:5: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack([v1, v2, v2])) # `row_stack` alias is deprecated. Use `np.vstack` directly.


In [47]:
# 2D arrays
v1 = np.zeros((2, 3))
v2 = np.ones((2, 3))

# print(np.row_stack([v1, v2, v2])) # `row_stack` alias is deprecated. Use `np.vstack` directly.
print(np.vstack([v1, v2]))
print()
print(np.hstack([v1, v2]))
print()
print(np.column_stack([v1, v2]))
print()



[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]



### Doing mathematical operations in NumPy Arrays

#### Elementwise Operations

In [48]:
a = np.array([1, 2, 3, 4])
print(a)
print(a, "+ 2 = ", a + 2)
print(a, "- 2 = ", a - 2)
print(a, "* 2 = ", a * 2)
print(a, "/ 2 = ", a / 2)
print(a, "% 2 = ", a % 2)
print(a, "// 2 = ", a // 2)
print(a, "** 2 = ", a ** 2)

[1 2 3 4]
[1 2 3 4] + 2 =  [3 4 5 6]
[1 2 3 4] - 2 =  [-1  0  1  2]
[1 2 3 4] * 2 =  [2 4 6 8]
[1 2 3 4] / 2 =  [0.5 1.  1.5 2. ]
[1 2 3 4] % 2 =  [1 0 1 0]
[1 2 3 4] // 2 =  [0 1 1 2]
[1 2 3 4] ** 2 =  [ 1  4  9 16]


In [49]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 2, 1])
print(a, " + ", b, " = ", a + b)
print(a, " * ", b, " = ", a * b)

[1 2 3 4]  +  [1 2 2 1]  =  [2 4 5 5]
[1 2 3 4]  *  [1 2 2 1]  =  [1 4 6 4]


#### Boolean Operations

In [50]:
a = np.array([[6, 1, 8], [3, 9, 8], [5, 2, 1]])
print(a, "\n")

print(a < 5)

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

[[False  True False]
 [ True False False]
 [False  True  True]]


In [52]:
print(a, "\n")
print(a[a < 5]) # print all elements of `a` which are less than 5
print()
print(a[a >= 5]) # print all elements of `a` which are greater than or equal to 5

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

[1 3 2 1]

[6 8 9 8 5]


In [53]:
print(a, "\n")

# check for whole nd array
print(np.any(a >= 8), "\n")

# check in particular axis
print(np.any(a >= 8, axis = 0), "\n") # 0 means column
print(np.any(a >= 8, axis = 1), "\n") # 1 means row

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

True 

[False  True  True] 

[ True  True False] 



In [54]:
print(a, "\n")

# check for whole nd array
print(np.all(a >= 3), "\n")

# check in particular axis
print(np.all(a >= 3, axis = 0), "\n") # 0 means column
print(np.all(a >= 3, axis = 1), "\n") # 1 means row

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

False 

[ True False False] 

[False  True False] 



In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])
print(a, "\n")

print(a[2:4, 0:2], "\n")
print(a[[0, 1, 2, 3], [1, 2, 3, 4]], "\n")
print(a[[0, 4, 5], 3:], "\n")

#### Matrix and Linear Algebra

In [ ]:
a = np.array([[2, 3], [3, 4]])
print(a, "\n")

b = np.array([[1, 2, 3], [2, 3, 1]])
print(b, "\n")

print(np.matmul(a, b), "\n")
# print(np.matmul(b, a), "\n") # this will give an error as they are not compatible for matrix multiplication

print("Determinant of a = ", round(np.linalg.det(a), 2), "\n")

print("Inverse of a = ")
print(np.linalg.inv(a), "\n")

#### Statistical Operation

In [ ]:
stats = np.array([[6, 1, 8, 0], [3, 9, 8, 7]])
print(stats, "\n")

print(np.min(stats))
print(np.min(stats, axis = 0))
print(np.min(stats, axis = 1), "\n")

print(np.max(stats))
print(np.max(stats, axis = 0))
print(np.max(stats, axis = 1), "\n")

print(np.sum(stats))
print(np.sum(stats, axis = 0))
print(np.sum(stats, axis = 1), "\n")
