## About Numpy

NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

Although Python lists are excellent, general-purpose containers. They can be `heterogeneous`, meaning that they can contain elements of a variety of types.

On the other hand, most NumPy arrays have some restrictions. For instance:
- They must be `homogeneous`, i.e. All elements of the array must be of the same type of data.
- Once created, the total size of the array can’t change.
- The shape must be `rectangular`, not jagged; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks.

## Installing and Importing

To install Numpy as a package:

```shell
>> pip install numpy
```

To import numpy:

In [7]:
import numpy as np

## Initialising numpy arrays

### Initialising arrays from Python sequences

One way to initialize an array is using a Python sequence, such as a `list` or a `tuple`.
to initialize an array from a sequence, we use `np.array()`.

We can also `np.array()` on another array to make a new copy of it.

In [ ]:
myList = [5, 2, 1, 4]
print(type(myList), myList)
myTuple = (5, 2, 1, 4)
print(type(myTuple), myTuple)

print()
fromTuple = np.array(myTuple)
print(type(fromTuple), fromTuple)
fromList = np.array(myList)
print(type(fromList), fromList)
fromArray = np.array(fromList)
print(type(fromArray), fromArray)

a = fromArray
print(f"\narray = {a}")
print(f"dimension            = {a.ndim}")
print(f"shape                = {a.shape}")
print(f"data type            = {a.dtype}")
print(f"no of elements       = {len(a)}")
print(f"no of elements       = {a.size}")
print(f"size of each element = {a.itemsize}")
print(f"size of array        = {a.size * a.itemsize}")
print(f"size of array        = {a.nbytes}")

<class 'list'> [5, 2, 1, 4]
<class 'tuple'> (5, 2, 1, 4)

<class 'numpy.ndarray'> [5 2 1 4]
<class 'numpy.ndarray'> [5 2 1 4]
<class 'numpy.ndarray'> [5 2 1 4]

array = [5 2 1 4]
dimension            = 1
shape                = (4,)
data type            = int64
no of elements       = 4
no of elements       = 4
size of each element = 8
size of array        = 32
size of array        = 32


we can also initialize a multi-dimensional array using a `nested list` or `nested tuple`.

In [129]:
nested = np.array([[9.1, 8.2, 7.3], [3.7, 2.8, 1.9]], dtype="float32")
print(nested)
print(f"dimension = {nested.ndim}")
print(f"shape     = {nested.shape}")
print(f"length    = {len(nested)}")
print(f"size      = {nested.size}")

[[9.1 8.2 7.3]
 [3.7 2.8 1.9]]
dimension = 2
shape     = (2, 3)
length    = 2
size      = 6


we can also initialize an array using a `list comprehension`.

In [152]:
evenNums = np.array([i+2 for i in range(0, 40, 2)])
print(evenNums)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


### Special constructors in Numpy

`np.arange()` creates an array with regularly spaced values within a given interval.
It's similar to Python's built-in `range()`, but it returns a NumPy array and supports decimal (float) steps.

In [ ]:
arr = np.arange(5)
print(f"arr = {arr}")

arr = np.arange(2, 10)
print(f"arr = {arr}")

arr = np.arange(2, 10, 2)
print(f"arr = {arr}") 

arr = np.arange(0, 1, 0.2, dtype=int)
print(f"arr = {arr}")

arr = np.arange(1, 6, dtype=float)
print(f"arr = {arr}") 

arr = [0 1 2 3 4]
arr = [2 3 4 5 6 7 8 9]
arr = [2 4 6 8]
arr = [0 0 0 0 0]
arr = [1. 2. 3. 4. 5.]


`np.linspace()` returns `n` evenly spaced numbers over a specified interval, including both the `start` and `stop` values.

In [18]:
start, stop, n = 0, 1, 5

arr = np.linspace(start, stop, n)
print(f"arr = {arr}")

arr = np.linspace(start, stop, n, endpoint=False)
print(f"arr = {arr}")

arr, step = np.linspace(start, stop, n, retstep=True)
print(f"arr = {arr}, stepsize = {step}")

arr = np.linspace(start, stop, n, dtype=int)
print(f"arr = {arr}")

arr = [0.   0.25 0.5  0.75 1.  ]
arr = [0.  0.2 0.4 0.6 0.8]
arr = [0.   0.25 0.5  0.75 1.  ], stepsize = 0.25
arr = [0 0 0 0 1]


In [138]:
print("nd array with all zeros")
m = np.zeros((3, 4))
print(m)
print(f"Default data type = {m.dtype}\n")

print("nd array with all zeros")
m = np.ones((3, 4))
print(m)
print(f"Default data type = {m.dtype}\n")

print("nd array with all same value")
value = 7
m = np.full((3, 4), value)
print(m)
print(f"Default data type = {m.dtype}\n")

print("nd array as identity matrix")
m = np.identity(4)
print(m)
print(f"Default data type = {m.dtype}\n")

nd array with all zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Default data type = float64

nd array with all zeros
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Default data type = float64

nd array with all same value
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Default data type = int64

nd array as identity matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Default data type = float64



### Numpy random module

`np.random` is NumPy’s random number generation module, used for creating random numbers, arrays, distributions, shuffling, and more.

In [22]:
print("\nnp.random.rand gives random number between 0 & 1.\n")
m = np.random.rand(3, 4) # gives a 2d array
print(m, "\n")
m = np.random.rand(3) # gievs a 1d array
print(m, "\n")
m = np.random.rand() # gives a scalar
print(m, "\n")

print("\nnp.random.randint gives random ints in given range.\n")
m = np.random.randint(1, 7, size=(3, 4)) # gives a 2d array
print(m, "\n")
m = np.random.randint(1, 7, size=(3)) # gives a 1d array
print(m, "\n")
m = np.random.randint(1, 7) # gives a scalar
print(m, "\n")

print("\nnp.random.normal gives random numbers from normal distribution.\n")
m = np.random.normal(loc=10, scale=1, size=(5))  # Mean=10, Std=2
print(m, "\n")

print("\nnp.random.choice picks random elements from given array (with or without replacements).\n")
m = np.random.choice(100, size=(5), replace=False)
print(m, "\n")
m = np.random.choice([5, 2, 1, 4], size=(5), replace=True)
print(m, "\n")


np.random.rand gives random number between 0 & 1.

[[0.9328107  0.84374335 0.12136254 0.97571921]
 [0.61002842 0.56085605 0.63508699 0.33370561]
 [0.71527564 0.54843585 0.59688532 0.40816962]] 

[0.38552753 0.46003516 0.38709984] 

0.2680593296856547 


np.random.randint gives random ints in given range.

[[3 5 3 3]
 [1 2 1 3]
 [3 3 5 2]] 

[3 1 1] 

4 


np.random.normal gives random numbers from normal distribution.

[10.58179436 10.29577018  8.90332759  9.6547822  10.01978683] 


np.random.choice picks random elements from given array (with or without replacements).

[73 23 78 55 50] 

[1 4 4 4 2] 



### Making copy of an array

Directly assigning one array onto another using `=` operator creates a shallow copy, ie, both variableNames point to the same memory locations

In [154]:
# shallow copy
print("before")

a = np.array([1, 2, 3, 4])
print("a = ", a)

s = a
print("s = ", s)

a[1] = 100
s[2] = 200

print("after")
print("a = ", a)
print("s = ", s)

before
a =  [1 2 3 4]
s =  [1 2 3 4]
after
a =  [  1 100 200   4]
s =  [  1 100 200   4]


In [48]:
# deep copy
print("before")
a = np.array([1, 2, 3, 4])
print("a = ", a)

b = np.array(a)
print("b = ", b)
c = a.copy()
print("c = ", c)

a[0] = 100
b[1] = 200
c[2] = 300

print("after")
print("a = ", a)
print("b = ", b)
print("c = ", c)

before
a =  [1 2 3 4]
b =  [1 2 3 4]
c =  [1 2 3 4]
after
a =  [100   2   3   4]
b =  [  1 200   3   4]
c =  [  1   2 300   4]


### Reshaping

In [153]:
a = [[6, 1, 8, 0], [3, 9, 8, 7]]
print(a)
before = np.array(a)
print(before)
print(f"shape = {before.shape}\ndim = {before.ndim}\n")

after = before.reshape((4,2)) # it is Not the same as transpose
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((1, 8)) # it still is 2D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((8, )) # now it is 1D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((2, 2, 2)) # now it is 3D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

#after = before.reshape((2, 3))
# this causes error as the no of elements dont match

[[6, 1, 8, 0], [3, 9, 8, 7]]
[[6 1 8 0]
 [3 9 8 7]]
shape = (2, 4)
dim = 2

[[6 1]
 [8 0]
 [3 9]
 [8 7]]
shape = (4, 2)
dim = 2

[[6 1 8 0 3 9 8 7]]
shape = (1, 8)
dim = 2

[6 1 8 0 3 9 8 7]
shape = (8,)
dim = 1

[[[6 1]
  [8 0]]

 [[3 9]
  [8 7]]]
shape = (2, 2, 2)
dim = 3



#### Indexing in arrays

In [ ]:
arr = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(arr, "\n")

print("Dimensions of the array: ",arr.shape) # (3, 4)

# using indexing to print elements individually

print("\nUsing [i][j] notation")
for i in range (arr.shape[0]):
    for j in range (arr.shape[1]):
        print(arr[i][j], end = "  ")
    print("")

print("\nUsing [i, j] notation")
for i in range (arr.shape[0]):
    for j in range (arr.shape[1]):
        print(arr[i, j], end = "  ")
    print("")

1
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]] 

Dimensions of the array:  (3, 4)

Using [i][j] notation
11  12  13  14  
21  22  23  24  
31  32  33  34  

Using [i, j] notation
11  12  13  14  
21  22  23  24  
31  32  33  34  


In [ ]:
a = np.array([6, 1, 8, 0, 3, 9, 8, 8, 7])

print(a)
print(a[2])
print(a[2], a[3], a[4])
print(a[2:5])
print(a[2:])
print(a[:5])
print(a[0:7:2])
print(a[:])
print(a[::])
print(a[::-1])

[6 1 8 0 3 9 8 8 7]
8
8 0 3
[8 0 3]
[8 0 3 9 8 8 7]
[6 1 8 0 3]
[6 8 3 8]
[6 1 8 0 3 9 8 8 7]
[6 1 8 0 3 9 8 8 7]
[7 8 8 9 3 0 8 1 6]


In [45]:
arr = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print("Dimensions of the array: ",arr.shape) # (3, 4)
print("arr = \n", arr)

# to get a specific row
print("\nPrinting Specific Rows")
print(arr[0])
print(arr[2, :])

# to get a specific column
print("\nPrinting Specific Cols")
print(arr[:, 0])
print(arr[:, 2])

# to get a specific sub-matrices
print("\nPrinting Specific submatrices")
print(arr[0:2, 1:3])

Dimensions of the array:  (3, 4)
arr = 
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

Printing Specific Rows
[11 12 13 14]
[31 32 33 34]

Printing Specific Cols
[11 21 31]
[13 23 33]

Printing Specific submatrices
[[12 13]
 [22 23]]


`Note:` The more you use ranged indexing the more dimensions the ouput array will have

In [91]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])
print(a, "\n")

print(a[2:4, 0:2], "\n")
print(a[[0, 1, 2, 3], [1, 2, 3, 4]], "\n")
print(a[[0, 4, 5], 3:], "\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

[[11 12]
 [16 17]] 

[ 2  8 14 20] 

[[ 4  5]
 [24 25]
 [29 30]] 



#### Stacking & Splitting

In [ ]:
# 1D arrays
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

st = np.vstack([v1, v2, v2])
print(st, "\n")
sp = np.vsplit(st, 3)
print(sp, "\n\n")

st = np.dstack([v1, v2, v2])
print(st, "\n")
sp = np.dsplit(st, 3)
print(sp, "\n\n")

st = np.hstack([v1, v2, v2])
print(st, "\n")
sp = np.hsplit(st, 3)
print(sp, "\n\n")

[[1 2 3]
 [4 5 6]
 [4 5 6]] 

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[4, 5, 6]])] 


[[[1 4 4]
  [2 5 5]
  [3 6 6]]] 

[array([[[1],
        [2],
        [3]]]), array([[[4],
        [5],
        [6]]]), array([[[4],
        [5],
        [6]]])] 


[1 2 3 4 5 6 4 5 6] 

[array([1, 2, 3]), array([4, 5, 6]), array([4, 5, 6])] 




In [90]:
# 2D arrays
v1 = np.zeros((2, 3))
v2 = np.ones((2, 3))

st = np.vstack([v1, v2, v2])
print(st, "\n")
sp = np.vsplit(st, 3)
print(sp, "\n\n")

st = np.dstack([v1, v2, v2])
print(st, "\n")
sp = np.dsplit(st, 3)
print(sp, "\n\n")

st = np.hstack([v1, v2, v2])
print(st, "\n")
sp = np.hsplit(st, 3)
print(sp, "\n\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[array([[0., 0., 0.],
       [0., 0., 0.]]), array([[1., 1., 1.],
       [1., 1., 1.]]), array([[1., 1., 1.],
       [1., 1., 1.]])] 


[[[0. 1. 1.]
  [0. 1. 1.]
  [0. 1. 1.]]

 [[0. 1. 1.]
  [0. 1. 1.]
  [0. 1. 1.]]] 

[array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]]), array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]]), array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])] 


[[0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1.]] 

[array([[0., 0., 0.],
       [0., 0., 0.]]), array([[1., 1., 1.],
       [1., 1., 1.]]), array([[1., 1., 1.],
       [1., 1., 1.]])] 




### Doing mathematical operations in NumPy Arrays

#### Elementwise Operations

In [35]:
# array with scalar
a = np.array([1, 2, 3, 4])
print(a)
print(a, "+ 2 = ", a + 2)
print(a, "- 2 = ", a - 2)
print(a, "* 2 = ", a * 2)
print(a, "/ 2 = ", a / 2)
print(a, "% 2 = ", a % 2)
print(a, "// 2 = ", a // 2)
print(a, "** 2 = ", a ** 2)

[1 2 3 4]
[1 2 3 4] + 2 =  [3 4 5 6]
[1 2 3 4] - 2 =  [-1  0  1  2]
[1 2 3 4] * 2 =  [2 4 6 8]
[1 2 3 4] / 2 =  [0.5 1.  1.5 2. ]
[1 2 3 4] % 2 =  [1 0 1 0]
[1 2 3 4] // 2 =  [0 1 1 2]
[1 2 3 4] ** 2 =  [ 1  4  9 16]


In [37]:
# array with array
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 2, 1])
print(a, " + ", b, " = ", a + b)
print(a, " - ", b, " = ", a - b)
print(a, " * ", b, " = ", a * b)
print(a, " / ", b, " = ", a / b)

[1 2 3 4]  +  [1 2 2 1]  =  [2 4 5 5]
[1 2 3 4]  -  [1 2 2 1]  =  [0 0 1 3]
[1 2 3 4]  *  [1 2 2 1]  =  [1 4 6 4]
[1 2 3 4]  /  [1 2 2 1]  =  [1.  1.  1.5 4. ]


#### Boolean Operations

In [50]:
a = np.array([[6, 1, 8], [3, 9, 8], [5, 2, 1]])
print(a, "\n")

print(a < 5)

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

[[False  True False]
 [ True False False]
 [False  True  True]]


In [92]:
a = np.array([[6, 1, 8], [3, 9, 8], [5, 2, 1]])
print(a, "\n")
print(a[a < 5]) # print all elements of `a` which are less than 5
print()
print(a[a > 10]) # print all elements of `a` which are greater than or equal to 5

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

[1 3 2 1]

[]


In [41]:
print(a, "\n")

# check for whole nd array
print(np.any(a >= 8), "\n")

# check in particular axis
print(np.any(a >= 8, axis = 0), "\n") # 0 means column
print(np.any(a >= 8, axis = 1), "\n") # 1 means row

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

True 

[False  True  True] 

[ True  True False] 



In [45]:
print(a, "\n")

# check for whole nd array
print(np.all(a >= 3), "\n")

# check in particular axis
print(np.all(a >= 3, axis = 0), "\n") # 0 means column
print(np.all(a >= 3, axis = 1), "\n") # 1 means row

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

False 

[ True False False] 

[False  True False] 



In [ ]:
a = np.array([1, 2, 3, 4, 5])
indices = np.where(a % 2 == 0)
print(indices)

a = np.array([ 1,  2,  3,  4,  5])
b = np.array([10, 20, 30, 40, 50])
result = np.where(a > 3, a, b) # WHERE (a > 3), pick elements from a ELSE, pick elements from b.
print(result)

a = np.array([0, -1, 2, -3, 4])
cleaned = np.where(a > 0, a, 0) # WHERE (a > 0), pick elements from a ELSE, pick 0.
print(cleaned)

(array([1, 3]),)
[10 20 30  4  5]
[0 0 2 0 4]


#### Matrix and Linear Algebra

In [ ]:
a = np.array([[2, 3], [3, 4]])
print(a, "\n")

b = np.array([[1, 2, 3], [2, 3, 1]])
print(b, "\n")

print(np.matmul(a, b), "\n")
# print(np.matmul(b, a), "\n") # this will give an error as they are not compatible for matrix multiplication

print("Determinant of a = ", round(np.linalg.det(a), 2), "\n")

print("Inverse of a = ")
print(np.linalg.inv(a), "\n")

#### Statistical Operation

In [47]:
stats = np.array([[6, 1, 8, 0], [3, 9, 8, 7]])
print(stats, "\n")

print(np.min(stats))
print(np.min(stats, axis = 0))
print(np.min(stats, axis = 1), "\n")

print(np.max(stats))
print(np.max(stats, axis = 0))
print(np.max(stats, axis = 1), "\n")

print(np.sum(stats))
print(np.sum(stats, axis = 0))
print(np.sum(stats, axis = 1), "\n")


[[6 1 8 0]
 [3 9 8 7]] 

0
[3 1 8 0]
[0 3] 

9
[6 9 8 7]
[8 9] 

42
[ 9 10 16  7]
[15 27] 

